# Generated by Django 3.0.1 on 2020-06-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amfi',
            fields=[
                ('sno', models.TextField(blank=True, null=True)),
                ('company_name', models.TextField(primary_key=True, serialize=False)),
                ('isin', models.TextField(blank=True, null=True)),
                ('bse_symbol', models.TextField(blank=True, null=True)),
                ('nse_symbol', models.TextField(blank=True, null=True)),
                ('avg_mcap', models.TextField(blank=True, null=True)),
                ('cap_type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'amfi',
                'managed': False,
            },
        ),
    ]
