# Generated by Django 3.1.5 on 2021-03-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('amfi', '0002_auto_20200710_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amfi',
            old_name='isin',
            new_name='comp_isin',
        ),
        migrations.RenameField(
            model_name='amfi',
            old_name='company_name',
            new_name='comp_name',
        ),
        migrations.RemoveField(
            model_name='amfi',
            name='sno',
        ),
        migrations.AddField(
            model_name='amfi',
            name='comp_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='amfi',
            table='global_amfi',
        ),
    ]
