# Generated by Django 3.0.1 on 2020-06-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nach',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('ticker', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nach',
                'managed': False,
            },
        ),
    ]
