# Generated by Django 3.0.1 on 2020-07-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('cap_type', models.TextField(primary_key=True, serialize=False)),
                ('cap_weight', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'global_weight',
            },
        ),
    ]
