# Generated by Django 3.1.5 on 2021-03-07 16:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('demattxn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demattxn',
            name='comp_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demattxn',
            name='dt_id',
            field=models.AutoField(default=django.utils.timezone.now, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='demattxn',
            unique_together={('comp_name', 'txn_date')},
        ),
        migrations.RemoveField(
            model_name='demattxn',
            name='company_name',
        ),
    ]
