# Generated by Django 3.1.5 on 2021-03-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BstmtDiv',
            fields=[
                ('bsdiv_id', models.TextField(primary_key=True, serialize=False)),
                ('bsdiv_date', models.DateField(blank=True, null=True)),
                ('bsdiv_remarks', models.TextField(blank=True, null=True)),
                ('bsdiv_amount', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_bstmt_div',
                'managed': False,
            },
        ),
    ]
