# Generated by Django 3.1.5 on 2021-03-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ftwhl',
            fields=[
                ('ftwhl_ticker', models.TextField(primary_key=True, serialize=False)),
                ('ftwhl_high', models.TextField(blank=True, null=True)),
                ('ftwhl_high_dt', models.TextField(blank=True, null=True)),
                ('ftwhl_low', models.TextField(blank=True, null=True)),
                ('ftwhl_low_dt', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'global_ftwhl',
            },
        ),
    ]
