# Generated by Django 3.1.5 on 2021-03-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trendlyne',
            fields=[
                ('tl_stock_name', models.TextField(blank=True, null=True)),
                ('tl_isin', models.TextField(primary_key=True, serialize=False)),
                ('tl_bat', models.FloatField(blank=True, null=True)),
                ('tl_der', models.FloatField(blank=True, null=True)),
                ('tl_roce3', models.FloatField(blank=True, null=True)),
                ('tl_roe3', models.FloatField(blank=True, null=True)),
                ('tl_dpr2', models.FloatField(blank=True, null=True)),
                ('tl_sales2', models.FloatField(blank=True, null=True)),
                ('tl_profit5', models.FloatField(blank=True, null=True)),
                ('tl_icr', models.FloatField(blank=True, null=True)),
                ('tl_pledge', models.FloatField(blank=True, null=True)),
                ('tl_low_3y', models.FloatField(blank=True, null=True)),
                ('tl_low_5y', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'global_trendlyne',
            },
        ),
    ]
