# Generated by Django 3.1.5 on 2021-03-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dematsum', '0002_auto_20200710_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dematsum',
            old_name='company_name',
            new_name='comp_name',
        ),
        migrations.AlterField(
            model_name='dematsum',
            name='acp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dematsum',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dematsum',
            name='value_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dematsum',
            name='value_market',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
