# Generated by Django 3.1.5 on 2021-03-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gfundareco',
            fields=[
                ('funda_reco_ticker', models.TextField(primary_key=True, serialize=False)),
                ('funda_reco_isin', models.TextField(blank=True, null=True)),
                ('funda_reco_type', models.TextField(blank=True, null=True)),
                ('funda_reco_cause', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'global_funda_reco',
            },
        ),
    ]
