# Generated by Django 3.1.5 on 2021-03-07 16:32

from django.db import migrations, models
import django_gotolong.uploaddoc.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadDocModel',
            fields=[
                ('uploaddoc_id', models.AutoField(primary_key=True, serialize=False)),
                ('uploaddoc_scope',
                 models.CharField(choices=[('input-global-data', '---GLOBAL---'), ('input-user-data', '---USER---')],
                                  max_length=255)),
                ('uploaddoc_type', models.CharField(
                    choices=[('global', '---GLOBAL---'), ('amfi', 'AMFI'), ('bhav', 'BHAV'), ('ftwhl', 'FTWHL'),
                             ('isin', 'ISIN'), ('nach', 'NACH'), ('screener', 'SCREENER'), ('trendlyne', 'TRNDLYNE'),
                             ('gweight', 'WEIGHT'), ('user', '---USER---'), ('dematsum', 'DEMATSUM'),
                             ('dematxn', 'DEMATTXN'), ('dividend', 'DIVIDEND')], max_length=255)),
                ('uploaddoc_year', models.CharField(blank=True, choices=[('all', 'ALL'), ('latest', 'LATEST'),
                                                                         ('FY 2011-2012', 'FY 2011-2012'),
                                                                         ('FY 2012-2013', 'FY 2012-2013'),
                                                                         ('FY 2013-2014', 'FY 2013-2014'),
                                                                         ('FY 2014-2015', 'FY 2014-2015'),
                                                                         ('FY 2015-2016', 'FY 2015-2016'),
                                                                         ('FY 2016-2017', 'FY 2016-2017'),
                                                                         ('FY 2017-2018', 'FY 2017-2018'),
                                                                         ('FY 2018-2019', 'FY 2018-2019'),
                                                                         ('FY 2019-2020', 'FY 2019-2020'),
                                                                         ('FY 2020-2021', 'FY 2020-2021'),
                                                                         ('FY 2021-2022', 'FY 2021-2022')],
                                                    max_length=255)),
                ('uploaddoc_fpath',
                 models.FileField(upload_to=django_gotolong.uploaddoc.models.UploadDocModel.file_rename)),
            ],
            options={
                'db_table': 'user_doc',
            },
        ),
    ]
