# Generated by Django 3.0.1 on 2020-06-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DematSummary',
            fields=[
                ('stock_symbol', models.TextField(primary_key=True, serialize=False)),
                ('company_name', models.TextField(blank=True, null=True)),
                ('isin_code', models.TextField(blank=True, null=True)),
                ('qty', models.TextField(blank=True, null=True)),
                ('acp', models.TextField(blank=True, null=True)),
                ('cmp', models.TextField(blank=True, null=True)),
                ('pct_change', models.TextField(blank=True, null=True)),
                ('value_cost', models.TextField(blank=True, null=True)),
                ('value_market', models.TextField(blank=True, null=True)),
                ('days_gain', models.TextField(blank=True, null=True)),
                ('days_gain_pct', models.TextField(blank=True, null=True)),
                ('realized_pl', models.TextField(blank=True, null=True)),
                ('unrealized_pl', models.TextField(blank=True, null=True)),
                ('unrealized_pl_pct', models.TextField(blank=True, null=True)),
                ('unused1', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'demat_summary',
                'managed': False,
            },
        ),
    ]
