#!/usr/bin/env python

import sys

import gotolong.nach.nach

import gotolong.config.config_json

sys.argv = ['config_json.py', 'nach']
cmd_line = gotolong.config.config_json.main()
print(cmd_line)

cmd_line_list = cmd_line.split(' ')
print(cmd_line_list)

cmd_line_list.insert(0, 'nach.py')

# NOTE: Is it good to modify the sys.argv
sys.argv = cmd_line_list
gotolong.nach.nach.main()
