#!/usr/bin/env python

import sys

import gotolong.ftwhl.ftwhl

import gotolong.config.config_json

sys.argv = ['config_json.py', 'ftwhl']
cmd_line = gotolong.config.config_json.main()
print(cmd_line)

cmd_line_list = cmd_line.split(' ')
print(cmd_line_list)

cmd_line_list.insert(0, 'ftwhl.py')

# NOTE: Is it good to modify the sys.argv
sys.argv = cmd_line_list
gotolong.ftwhl.ftwhl.main()
