#!/usr/bin/env python

import sys

import amfi.amfi

import cutil.config_json

sys.argv = ['config_json.py', 'amfi']
cmd_line = cutil.config_json.main()
print(cmd_line)

cmd_line_list = cmd_line.split(' ')
print(cmd_line_list)

cmd_line_list.insert(0, 'amfi.py')

# NOTE: Is it good to modify the sys.argv
sys.argv = cmd_line_list
amfi.amfi.main()
