#!/usr/bin/env python

import sys

import gotolong.bhav.bhav

import gotolong.config.config_json

sys.argv = ['config_json.py', 'bhav']
cmd_line = gotolong.config.config_json.main()
print(cmd_line)

cmd_line_list = cmd_line.split(' ')
print(cmd_line_list)

cmd_line_list.insert(0, 'bhav.py')

# NOTE: Is it good to modify the sys.argv
sys.argv = cmd_line_list
gotolong.bhav.bhav.main()
