#!/usr/bin/env python

import sys

import global_weight.gweight

import cutil.config_json

sys.argv = ['config_json.py', 'gweight']
cmd_line = cutil.config_json.main()
print(cmd_line)

cmd_line_list = cmd_line.split(' ')
print(cmd_line_list)

cmd_line_list.insert(0, 'gweight.py')

# NOTE: Is it good to modify the sys.argv
sys.argv = cmd_line_list
global_weight.gweight.main()
