# Generated by Django 3.1.5 on 2021-03-07 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nach', '0002_auto_20200710_1928'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nach',
            table='global_nach',
        ),
    ]
