#!/usr/bin/env python

import sys

import demat.demat

import cutil.config_json

cmd_line = cutil.config_json.main(['config_json.py', 'demat'])
print(cmd_line)

cmd_line_list = cmd_line.split(' ')
print(cmd_line_list)

cmd_line_list.insert(0, 'demat.py')

# NOTE: Is it good to modify the sys.argv
sys.argv = cmd_line_list
demat.demat.main()
