# Generated by Django 3.1.5 on 2021-03-07 16:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('gweight', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Weight',
            new_name='Gweight',
        ),
        migrations.RenameField(
            model_name='gweight',
            old_name='cap_type',
            new_name='gw_cap_type',
        ),
        migrations.RenameField(
            model_name='gweight',
            old_name='cap_weight',
            new_name='gw_cap_weight',
        ),
    ]
