# Generated by Django 3.0.1 on 2020-07-10 13:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('nach', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nach',
            options={},
        ),
    ]
